# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dell\Desktop\Metallographic-detection-platform-based-on-DL\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1222, 850)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgs/cqu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    border-image: url(:/imgs/real_bg.png);\n"
"border-radius: 10px;\n"
"border:10px solid grey;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.title_frame = MyTitleWidget(self.centralwidget)
        self.title_frame.setMinimumSize(QtCore.QSize(0, 75))
        self.title_frame.setObjectName("title_frame")
        self.verticalLayout_5.addWidget(self.title_frame)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(5, -1, 15, 5)
        self.horizontalLayout_5.setSpacing(13)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.leftList = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.leftList.setFont(font)
        self.leftList.setStyleSheet("\n"
"QListWidget\n"
"{\n"
"outline:0px;\n"
"border-radius:5px;\n"
"background-color: rgb(249, 249, 251);\n"
"border:2px solid white; \n"
"}\n"
"\n"
"QListWidget::Item:hover\n"
"{\n"
"background:skyblue;\n"
"padding-top:0px;\n"
"padding-bottom:0px;\n"
"}\n"
"QListWidget::item:selected\n"
"{\n"
"   background:rgb(248,248,255); color:rgb(65,105,225);\n"
"   border-left: 8px solid rgb(65,105,225);\n"
"\n"
"}\n"
"QListWidget::item:selected:!active\n"
"{\n"
"active\n"
"{\n"
"border-width:0px;background:lightgreen;\n"
"}\n"
"}\n"
"QListView::item\n"
"{\n"
"    height:60px;\n"
"}")
        self.leftList.setIconSize(QtCore.QSize(40, 40))
        self.leftList.setObjectName("leftList")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/imgs/real_Home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.leftList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        item.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/imgs/real_Eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.Dense1Pattern)
        item.setForeground(brush)
        self.leftList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        item.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/imgs/real_Browser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.leftList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        item.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/imgs/real_Community.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.leftList.addItem(item)
        self.horizontalLayout_5.addWidget(self.leftList)
        self.pages = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pages.sizePolicy().hasHeightForWidth())
        self.pages.setSizePolicy(sizePolicy)
        self.pages.setStyleSheet("#pages{\n"
"    \n"
"border-radius:5px;\n"
"background:transparent;\n"
"} \n"
"")
        self.pages.setLineWidth(1)
        self.pages.setObjectName("pages")
        self.home_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_page.sizePolicy().hasHeightForWidth())
        self.home_page.setSizePolicy(sizePolicy)
        self.home_page.setStyleSheet("")
        self.home_page.setObjectName("home_page")
        self.home_label = QtWidgets.QLabel(self.home_page)
        self.home_label.setGeometry(QtCore.QRect(10, 60, 921, 611))
        self.home_label.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(66, 115, 186, 255), stop:1 rgba(63, 158, 201, 255));\n"
"border-radius:10px;")
        self.home_label.setText("")
        self.home_label.setPixmap(QtGui.QPixmap(":/imgs/main_page.png"))
        self.home_label.setScaledContents(True)
        self.home_label.setObjectName("home_label")
        self.pages.addWidget(self.home_page)
        self.predict_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predict_page.sizePolicy().hasHeightForWidth())
        self.predict_page.setSizePolicy(sizePolicy)
        self.predict_page.setObjectName("predict_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.predict_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(15, 10, 10, 10)
        self.horizontalLayout.setSpacing(25)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.p_left_frame = QtWidgets.QFrame(self.predict_page)
        self.p_left_frame.setStyleSheet("#p_left_frame{\n"
"border-radius:5px;\n"
"background-color: rgb(250, 250, 252);\n"
"}")
        self.p_left_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.p_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p_left_frame.setObjectName("p_left_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.p_left_frame)
        self.verticalLayout.setSpacing(26)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(10, 20, 10, 0)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.p_left_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:black;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.p_example_pb = QtWidgets.QPushButton(self.p_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_example_pb.sizePolicy().hasHeightForWidth())
        self.p_example_pb.setSizePolicy(sizePolicy)
        self.p_example_pb.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.p_example_pb.setFont(font)
        self.p_example_pb.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 170, 0);\n"
"border-radius:7px;\n"
"color:white;\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(255, 255, 91); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(255, 255, 22); \n"
"}")
        self.p_example_pb.setCheckable(False)
        self.p_example_pb.setObjectName("p_example_pb")
        self.horizontalLayout_6.addWidget(self.p_example_pb)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.p_add_pb = QtWidgets.QPushButton(self.p_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_add_pb.sizePolicy().hasHeightForWidth())
        self.p_add_pb.setSizePolicy(sizePolicy)
        self.p_add_pb.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.p_add_pb.setFont(font)
        self.p_add_pb.setStyleSheet("\n"
"QPushButton{\n"
"    background-color: rgb(243, 250, 255);\n"
"border-radius:3px;\n"
"border:2px solid rgb(176, 196, 234); \n"
"\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(229, 241, 251); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(199, 255, 255); \n"
"}")
        self.p_add_pb.setObjectName("p_add_pb")
        self.verticalLayout_6.addWidget(self.p_add_pb)
        self.p_sub_pb = QtWidgets.QPushButton(self.p_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_sub_pb.sizePolicy().hasHeightForWidth())
        self.p_sub_pb.setSizePolicy(sizePolicy)
        self.p_sub_pb.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.p_sub_pb.setFont(font)
        self.p_sub_pb.setStyleSheet("QPushButton{\n"
"    background-color: rgb(243, 250, 255);\n"
"border-radius:3px;\n"
"border:2px solid rgb(176, 196, 234); \n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(229, 241, 251); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(199, 255, 255); \n"
"}")
        self.p_sub_pb.setObjectName("p_sub_pb")
        self.verticalLayout_6.addWidget(self.p_sub_pb)
        self.horizontalLayout_12.addLayout(self.verticalLayout_6)
        self.p_smile_tableWidget = QtWidgets.QTableWidget(self.p_left_frame)
        self.p_smile_tableWidget.setStyleSheet("QTableWidget{\n"
"border-radius:7px;\n"
"font: 75 9pt \"微软雅黑\";\n"
"background-color: rgb(255, 255, 255);\n"
"border:2px solid rgb(176, 196, 234); \n"
"}\n"
"")
        self.p_smile_tableWidget.setRowCount(1)
        self.p_smile_tableWidget.setColumnCount(1)
        self.p_smile_tableWidget.setObjectName("p_smile_tableWidget")
        self.p_smile_tableWidget.horizontalHeader().setVisible(False)
        self.p_smile_tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.p_smile_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.p_smile_tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.p_smile_tableWidget.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_12.addWidget(self.p_smile_tableWidget)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 18)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.p_help_pb = QtWidgets.QPushButton(self.p_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_help_pb.sizePolicy().hasHeightForWidth())
        self.p_help_pb.setSizePolicy(sizePolicy)
        self.p_help_pb.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.p_help_pb.setFont(font)
        self.p_help_pb.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 170, 0);\n"
"border-radius:7px;\n"
"color:white;\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(255, 255, 91); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(255, 255, 22); \n"
"}")
        self.p_help_pb.setObjectName("p_help_pb")
        self.verticalLayout.addWidget(self.p_help_pb)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.p_left_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:black;")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.p_upload_pb = QtWidgets.QPushButton(self.p_left_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.p_upload_pb.setFont(font)
        self.p_upload_pb.setStyleSheet("\n"
"QPushButton{\n"
"background:transparent;\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(225, 225, 225); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(255, 255, 255); \n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/imgs/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.p_upload_pb.setIcon(icon5)
        self.p_upload_pb.setIconSize(QtCore.QSize(40, 40))
        self.p_upload_pb.setObjectName("p_upload_pb")
        self.horizontalLayout_3.addWidget(self.p_upload_pb)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.p_file_lineEdit = QtWidgets.QLineEdit(self.p_left_frame)
        self.p_file_lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.p_file_lineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.p_file_lineEdit.setFont(font)
        self.p_file_lineEdit.setStyleSheet("background-color: rgb(243, 250, 255);\n"
"border-radius:7px;\n"
"border:2px solid rgb(176, 196, 234); ")
        self.p_file_lineEdit.setReadOnly(True)
        self.p_file_lineEdit.setObjectName("p_file_lineEdit")
        self.verticalLayout.addWidget(self.p_file_lineEdit)
        self.label_12 = QtWidgets.QLabel(self.p_left_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:black;")
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.p_algo_tabWidget = QtWidgets.QTabWidget(self.p_left_frame)
        self.p_algo_tabWidget.setStyleSheet("#p_algo_tabWidget{\n"
"background-color: rgb(243, 250, 255);\n"
"font: 75 9pt \"Adobe Gothic Std B\";\n"
"border-radius:7px;\n"
"}\n"
"")
        self.p_algo_tabWidget.setObjectName("p_algo_tabWidget")
        self.voc_tab = QtWidgets.QWidget()
        self.voc_tab.setObjectName("voc_tab")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.voc_tab)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.p_voc_comboBox = QtWidgets.QComboBox(self.voc_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_voc_comboBox.sizePolicy().hasHeightForWidth())
        self.p_voc_comboBox.setSizePolicy(sizePolicy)
        self.p_voc_comboBox.setMaximumSize(QtCore.QSize(12200, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.p_voc_comboBox.setFont(font)
        self.p_voc_comboBox.setAcceptDrops(False)
        self.p_voc_comboBox.setStyleSheet("QComboBox{\n"
"    \n"
"border-radius:7px;\n"
"background-color: rgb(243, 250, 255);\n"
"border:2px solid rgb(176, 196, 234); \n"
"selection-color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 38px;\n"
" \n"
"    border-left-width: 0px;\n"
"    border-left-color: rgb(239, 243, 248);\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/imgs/arrow_down_blue.png);\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox QScrollBar:vertical\n"
"{\n"
"    width:14px;\n"
"    background:rgba(176, 196, 234,0%);\n"
"    margin:0px,0px,0px,0px;\n"
"    padding-top:15px;  \n"
"    padding-bottom:15px;\n"
"}\n"
"QComboBox QScrollBar::handle:vertical\n"
"{\n"
"    width:14px;\n"
"    background:rgba(176, 196, 234,25%);\n"
"    border-radius:4px;  \n"
"    min-height:20;\n"
"}\n"
"QComboBox QScrollBar::handle:vertical:hover\n"
"{\n"
"    width:14px;\n"
"    background:rgba(176, 196, 234,50%); \n"
"    border-radius:4px;\n"
"    min-height:20;\n"
"}\n"
"\n"
"QComboBox QScrollBar::add-line:vertical \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_down_blue.png);\n"
"    \n"
"    subcontrol-position:bottom;\n"
"}\n"
"QComboBox QScrollBar::sub-line:vertical  \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_up_blue.png);\n"
"    subcontrol-position:top;\n"
"}\n"
"QComboBox QScrollBar::add-line:vertical:hover  \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_down.png);\n"
"    subcontrol-position:bottom;\n"
"}\n"
"QComboBox QScrollBar::sub-line:vertical:hover  \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_up.png);\n"
"    subcontrol-position:top;\n"
"}\n"
"QComboBox QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical  \n"
"{\n"
"    background:rgba(176, 196, 234,10%);\n"
"}\n"
"\n"
"")
        self.p_voc_comboBox.setEditable(False)
        self.p_voc_comboBox.setDuplicatesEnabled(False)
        self.p_voc_comboBox.setFrame(True)
        self.p_voc_comboBox.setObjectName("p_voc_comboBox")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.p_voc_comboBox.addItem("")
        self.horizontalLayout_16.addWidget(self.p_voc_comboBox)
        self.p_algo_tabWidget.addTab(self.voc_tab, "")
        self.jsc_tab = QtWidgets.QWidget()
        self.jsc_tab.setObjectName("jsc_tab")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.jsc_tab)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.p_jsc_comboBox = QtWidgets.QComboBox(self.jsc_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_jsc_comboBox.sizePolicy().hasHeightForWidth())
        self.p_jsc_comboBox.setSizePolicy(sizePolicy)
        self.p_jsc_comboBox.setMaximumSize(QtCore.QSize(12200, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.p_jsc_comboBox.setFont(font)
        self.p_jsc_comboBox.setAcceptDrops(False)
        self.p_jsc_comboBox.setStyleSheet("QComboBox{\n"
"    \n"
"border-radius:7px;\n"
"background-color: rgb(243, 250, 255);\n"
"border:2px solid rgb(176, 196, 234); \n"
"selection-color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 38px;\n"
" \n"
"    border-left-width: 0px;\n"
"    border-left-color: rgb(239, 243, 248);\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/imgs/arrow_down_blue.png);\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox QScrollBar:vertical\n"
"{\n"
"    width:14px;\n"
"    background:rgba(176, 196, 234,0%);\n"
"    margin:0px,0px,0px,0px;\n"
"    padding-top:15px;  \n"
"    padding-bottom:15px;\n"
"}\n"
"QComboBox QScrollBar::handle:vertical\n"
"{\n"
"    width:14px;\n"
"    background:rgba(176, 196, 234,25%);\n"
"    border-radius:4px;  \n"
"    min-height:20;\n"
"}\n"
"QComboBox QScrollBar::handle:vertical:hover\n"
"{\n"
"    width:14px;\n"
"    background:rgba(176, 196, 234,50%); \n"
"    border-radius:4px;\n"
"    min-height:20;\n"
"}\n"
"\n"
"QComboBox QScrollBar::add-line:vertical \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_down_blue.png);\n"
"    \n"
"    subcontrol-position:bottom;\n"
"}\n"
"QComboBox QScrollBar::sub-line:vertical  \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_up_blue.png);\n"
"    subcontrol-position:top;\n"
"}\n"
"QComboBox QScrollBar::add-line:vertical:hover  \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_down.png);\n"
"    subcontrol-position:bottom;\n"
"}\n"
"QComboBox QScrollBar::sub-line:vertical:hover  \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_up.png);\n"
"    subcontrol-position:top;\n"
"}\n"
"QComboBox QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical  \n"
"{\n"
"    background:rgba(176, 196, 234,10%);\n"
"}\n"
"\n"
"")
        self.p_jsc_comboBox.setEditable(False)
        self.p_jsc_comboBox.setDuplicatesEnabled(False)
        self.p_jsc_comboBox.setFrame(True)
        self.p_jsc_comboBox.setObjectName("p_jsc_comboBox")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.p_jsc_comboBox.addItem("")
        self.horizontalLayout_15.addWidget(self.p_jsc_comboBox)
        self.p_algo_tabWidget.addTab(self.jsc_tab, "")
        self.ff_tab = QtWidgets.QWidget()
        self.ff_tab.setObjectName("ff_tab")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.ff_tab)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.p_ff_comboBox = QtWidgets.QComboBox(self.ff_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_ff_comboBox.sizePolicy().hasHeightForWidth())
        self.p_ff_comboBox.setSizePolicy(sizePolicy)
        self.p_ff_comboBox.setMaximumSize(QtCore.QSize(12200, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.p_ff_comboBox.setFont(font)
        self.p_ff_comboBox.setAcceptDrops(False)
        self.p_ff_comboBox.setStyleSheet("QComboBox{\n"
"    \n"
"border-radius:7px;\n"
"background-color: rgb(243, 250, 255);\n"
"border:2px solid rgb(176, 196, 234); \n"
"selection-color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 38px;\n"
" \n"
"    border-left-width: 0px;\n"
"    border-left-color: rgb(239, 243, 248);\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/imgs/arrow_down_blue.png);\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox QScrollBar:vertical\n"
"{\n"
"    width:14px;\n"
"    background:rgba(176, 196, 234,0%);\n"
"    margin:0px,0px,0px,0px;\n"
"    padding-top:15px;  \n"
"    padding-bottom:15px;\n"
"}\n"
"QComboBox QScrollBar::handle:vertical\n"
"{\n"
"    width:14px;\n"
"    background:rgba(176, 196, 234,25%);\n"
"    border-radius:4px;  \n"
"    min-height:20;\n"
"}\n"
"QComboBox QScrollBar::handle:vertical:hover\n"
"{\n"
"    width:14px;\n"
"    background:rgba(176, 196, 234,50%); \n"
"    border-radius:4px;\n"
"    min-height:20;\n"
"}\n"
"\n"
"QComboBox QScrollBar::add-line:vertical \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_down_blue.png);\n"
"    \n"
"    subcontrol-position:bottom;\n"
"}\n"
"QComboBox QScrollBar::sub-line:vertical  \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_up_blue.png);\n"
"    subcontrol-position:top;\n"
"}\n"
"QComboBox QScrollBar::add-line:vertical:hover  \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_down.png);\n"
"    subcontrol-position:bottom;\n"
"}\n"
"QComboBox QScrollBar::sub-line:vertical:hover  \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_up.png);\n"
"    subcontrol-position:top;\n"
"}\n"
"QComboBox QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical  \n"
"{\n"
"    background:rgba(176, 196, 234,10%);\n"
"}\n"
"\n"
"")
        self.p_ff_comboBox.setEditable(False)
        self.p_ff_comboBox.setDuplicatesEnabled(False)
        self.p_ff_comboBox.setFrame(True)
        self.p_ff_comboBox.setObjectName("p_ff_comboBox")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.p_ff_comboBox.addItem("")
        self.horizontalLayout_14.addWidget(self.p_ff_comboBox)
        self.p_algo_tabWidget.addTab(self.ff_tab, "")
        self.pce_tab = QtWidgets.QWidget()
        self.pce_tab.setObjectName("pce_tab")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.pce_tab)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.p_pce_comboBox = QtWidgets.QComboBox(self.pce_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_pce_comboBox.sizePolicy().hasHeightForWidth())
        self.p_pce_comboBox.setSizePolicy(sizePolicy)
        self.p_pce_comboBox.setMaximumSize(QtCore.QSize(12200, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.p_pce_comboBox.setFont(font)
        self.p_pce_comboBox.setAcceptDrops(False)
        self.p_pce_comboBox.setStyleSheet("QComboBox{\n"
"    \n"
"border-radius:7px;\n"
"background-color: rgb(243, 250, 255);\n"
"border:2px solid rgb(176, 196, 234); \n"
"selection-color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 38px;\n"
" \n"
"    border-left-width: 0px;\n"
"    border-left-color: rgb(239, 243, 248);\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/imgs/arrow_down_blue.png);\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox QScrollBar:vertical\n"
"{\n"
"    width:14px;\n"
"    background:rgba(176, 196, 234,0%);\n"
"    margin:0px,0px,0px,0px;\n"
"    padding-top:15px;  \n"
"    padding-bottom:15px;\n"
"}\n"
"QComboBox QScrollBar::handle:vertical\n"
"{\n"
"    width:14px;\n"
"    background:rgba(176, 196, 234,25%);\n"
"    border-radius:4px;  \n"
"    min-height:20;\n"
"}\n"
"QComboBox QScrollBar::handle:vertical:hover\n"
"{\n"
"    width:14px;\n"
"    background:rgba(176, 196, 234,50%); \n"
"    border-radius:4px;\n"
"    min-height:20;\n"
"}\n"
"\n"
"QComboBox QScrollBar::add-line:vertical \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_down_blue.png);\n"
"    \n"
"    subcontrol-position:bottom;\n"
"}\n"
"QComboBox QScrollBar::sub-line:vertical  \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_up_blue.png);\n"
"    subcontrol-position:top;\n"
"}\n"
"QComboBox QScrollBar::add-line:vertical:hover  \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_down.png);\n"
"    subcontrol-position:bottom;\n"
"}\n"
"QComboBox QScrollBar::sub-line:vertical:hover  \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_up.png);\n"
"    subcontrol-position:top;\n"
"}\n"
"QComboBox QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical  \n"
"{\n"
"    background:rgba(176, 196, 234,10%);\n"
"}\n"
"\n"
"")
        self.p_pce_comboBox.setEditable(False)
        self.p_pce_comboBox.setDuplicatesEnabled(False)
        self.p_pce_comboBox.setFrame(True)
        self.p_pce_comboBox.setObjectName("p_pce_comboBox")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.p_pce_comboBox.addItem("")
        self.horizontalLayout_13.addWidget(self.p_pce_comboBox)
        self.p_algo_tabWidget.addTab(self.pce_tab, "")
        self.verticalLayout.addWidget(self.p_algo_tabWidget)
        self.p_submit_pb = QtWidgets.QPushButton(self.p_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_submit_pb.sizePolicy().hasHeightForWidth())
        self.p_submit_pb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.p_submit_pb.setFont(font)
        self.p_submit_pb.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 207, 215);\n"
"border-radius:7px;\n"
"color:white;\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(90, 147, 209); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(81, 122, 238); \n"
"}")
        self.p_submit_pb.setObjectName("p_submit_pb")
        self.verticalLayout.addWidget(self.p_submit_pb)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(6, 1)
        self.verticalLayout.setStretch(7, 1)
        self.horizontalLayout.addWidget(self.p_left_frame)
        self.p_right_frame = QtWidgets.QFrame(self.predict_page)
        self.p_right_frame.setStyleSheet("#p_right_frame{\n"
"border-radius:5px;\n"
"background-color: rgb(250, 250, 252);\n"
"}")
        self.p_right_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.p_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p_right_frame.setObjectName("p_right_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.p_right_frame)
        self.verticalLayout_2.setSpacing(11)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.p_right_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.p_download_pb = QtWidgets.QPushButton(self.p_right_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.p_download_pb.setFont(font)
        self.p_download_pb.setStyleSheet("\n"
"QPushButton{\n"
"background:transparent;\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(225, 225, 225); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(255, 255, 255); \n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/imgs/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.p_download_pb.setIcon(icon6)
        self.p_download_pb.setIconSize(QtCore.QSize(40, 40))
        self.p_download_pb.setObjectName("p_download_pb")
        self.horizontalLayout_7.addWidget(self.p_download_pb)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout.addWidget(self.p_right_frame)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.pages.addWidget(self.predict_page)
        self.trans_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trans_page.sizePolicy().hasHeightForWidth())
        self.trans_page.setSizePolicy(sizePolicy)
        self.trans_page.setObjectName("trans_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.trans_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(15, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(25)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.t_left_frame = QtWidgets.QFrame(self.trans_page)
        self.t_left_frame.setStyleSheet("#t_left_frame{\n"
"border-radius:5px;\n"
"background-color: rgb(250, 250, 252);\n"
"}")
        self.t_left_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.t_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.t_left_frame.setObjectName("t_left_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.t_left_frame)
        self.verticalLayout_3.setSpacing(26)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(10, 20, 10, 0)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.t_left_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:black;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.t_example_pb = QtWidgets.QPushButton(self.t_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_example_pb.sizePolicy().hasHeightForWidth())
        self.t_example_pb.setSizePolicy(sizePolicy)
        self.t_example_pb.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.t_example_pb.setFont(font)
        self.t_example_pb.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 170, 0);\n"
"border-radius:7px;\n"
"color:white;\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(255, 255, 91); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(255, 255, 22); \n"
"}")
        self.t_example_pb.setCheckable(False)
        self.t_example_pb.setObjectName("t_example_pb")
        self.horizontalLayout_8.addWidget(self.t_example_pb)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.t_add_pb = QtWidgets.QPushButton(self.t_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_add_pb.sizePolicy().hasHeightForWidth())
        self.t_add_pb.setSizePolicy(sizePolicy)
        self.t_add_pb.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.t_add_pb.setFont(font)
        self.t_add_pb.setStyleSheet("\n"
"QPushButton{\n"
"    background-color: rgb(243, 250, 255);\n"
"border-radius:3px;\n"
"border:2px solid rgb(176, 196, 234); \n"
"\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(229, 241, 251); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(199, 255, 255); \n"
"}")
        self.t_add_pb.setObjectName("t_add_pb")
        self.verticalLayout_7.addWidget(self.t_add_pb)
        self.t_sub_pb = QtWidgets.QPushButton(self.t_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_sub_pb.sizePolicy().hasHeightForWidth())
        self.t_sub_pb.setSizePolicy(sizePolicy)
        self.t_sub_pb.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.t_sub_pb.setFont(font)
        self.t_sub_pb.setStyleSheet("QPushButton{\n"
"    background-color: rgb(243, 250, 255);\n"
"border-radius:3px;\n"
"border:2px solid rgb(176, 196, 234); \n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(229, 241, 251); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(199, 255, 255); \n"
"}")
        self.t_sub_pb.setObjectName("t_sub_pb")
        self.verticalLayout_7.addWidget(self.t_sub_pb)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.t_smile_tableWidget = QtWidgets.QTableWidget(self.t_left_frame)
        self.t_smile_tableWidget.setStyleSheet("QTableWidget{\n"
"border-radius:7px;\n"
"font: 75 9pt \"微软雅黑\";\n"
"background-color: rgb(255, 255, 255);\n"
"border:2px solid rgb(176, 196, 234); \n"
"}\n"
"\n"
"\n"
"")
        self.t_smile_tableWidget.setRowCount(1)
        self.t_smile_tableWidget.setColumnCount(1)
        self.t_smile_tableWidget.setObjectName("t_smile_tableWidget")
        self.t_smile_tableWidget.horizontalHeader().setVisible(False)
        self.t_smile_tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.t_smile_tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.t_smile_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.t_smile_tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.t_smile_tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.t_smile_tableWidget.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_10.addWidget(self.t_smile_tableWidget)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 18)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.t_help_pb = QtWidgets.QPushButton(self.t_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_help_pb.sizePolicy().hasHeightForWidth())
        self.t_help_pb.setSizePolicy(sizePolicy)
        self.t_help_pb.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.t_help_pb.setFont(font)
        self.t_help_pb.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 170, 0);\n"
"border-radius:7px;\n"
"color:white;\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(255, 255, 91); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(255, 255, 22); \n"
"}")
        self.t_help_pb.setObjectName("t_help_pb")
        self.verticalLayout_3.addWidget(self.t_help_pb)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.t_left_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.t_upload_pb = QtWidgets.QPushButton(self.t_left_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.t_upload_pb.setFont(font)
        self.t_upload_pb.setStyleSheet("\n"
"QPushButton{\n"
"background:transparent;\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(225, 225, 225); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(255, 255, 255); \n"
"}")
        self.t_upload_pb.setIcon(icon5)
        self.t_upload_pb.setIconSize(QtCore.QSize(40, 40))
        self.t_upload_pb.setObjectName("t_upload_pb")
        self.horizontalLayout_4.addWidget(self.t_upload_pb)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.t_file_lineEdit = QtWidgets.QLineEdit(self.t_left_frame)
        self.t_file_lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.t_file_lineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.t_file_lineEdit.setFont(font)
        self.t_file_lineEdit.setStyleSheet("background-color: rgb(243, 250, 255);\n"
"border-radius:7px;\n"
"border:2px solid rgb(176, 196, 234); ")
        self.t_file_lineEdit.setReadOnly(True)
        self.t_file_lineEdit.setObjectName("t_file_lineEdit")
        self.verticalLayout_3.addWidget(self.t_file_lineEdit)
        self.label_16 = QtWidgets.QLabel(self.t_left_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:black;")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.t_smile_comboBox = QtWidgets.QComboBox(self.t_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_smile_comboBox.sizePolicy().hasHeightForWidth())
        self.t_smile_comboBox.setSizePolicy(sizePolicy)
        self.t_smile_comboBox.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.t_smile_comboBox.setFont(font)
        self.t_smile_comboBox.setStyleSheet("QComboBox{\n"
"    \n"
"border-radius:7px;\n"
"background-color: rgb(243, 250, 255);\n"
"border:2px solid rgb(176, 196, 234); \n"
"selection-color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 38px;\n"
" \n"
"    border-left-width: 0px;\n"
"    border-left-color: rgb(239, 243, 248);\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/imgs/arrow_down_blue.png);\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox QScrollBar:vertical\n"
"{\n"
"    width:14px;\n"
"    background:rgba(176, 196, 234,0%);\n"
"    margin:0px,0px,0px,0px;\n"
"    padding-top:15px;  \n"
"    padding-bottom:15px;\n"
"}\n"
"QComboBox QScrollBar::handle:vertical\n"
"{\n"
"    width:14px;\n"
"    background:rgba(176, 196, 234,25%);\n"
"    border-radius:4px;  \n"
"    min-height:20;\n"
"}\n"
"QComboBox QScrollBar::handle:vertical:hover\n"
"{\n"
"    width:14px;\n"
"    background:rgba(176, 196, 234,50%); \n"
"    border-radius:4px;\n"
"    min-height:20;\n"
"}\n"
"\n"
"QComboBox QScrollBar::add-line:vertical \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_down_blue.png);\n"
"    \n"
"    subcontrol-position:bottom;\n"
"}\n"
"QComboBox QScrollBar::sub-line:vertical  \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_up_blue.png);\n"
"    subcontrol-position:top;\n"
"}\n"
"QComboBox QScrollBar::add-line:vertical:hover  \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_down.png);\n"
"    subcontrol-position:bottom;\n"
"}\n"
"QComboBox QScrollBar::sub-line:vertical:hover  \n"
"{\n"
"    height:14px;width:14px;\n"
"    border-image:url(:/imgs/arrow_up.png);\n"
"    subcontrol-position:top;\n"
"}\n"
"QComboBox QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical  \n"
"{\n"
"    background:rgba(176, 196, 234,10%);\n"
"}\n"
"\n"
"")
        self.t_smile_comboBox.setFrame(True)
        self.t_smile_comboBox.setObjectName("t_smile_comboBox")
        self.t_smile_comboBox.addItem("")
        self.t_smile_comboBox.addItem("")
        self.t_smile_comboBox.addItem("")
        self.t_smile_comboBox.addItem("")
        self.t_smile_comboBox.addItem("")
        self.t_smile_comboBox.addItem("")
        self.t_smile_comboBox.addItem("")
        self.t_smile_comboBox.addItem("")
        self.t_smile_comboBox.addItem("")
        self.t_smile_comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.t_smile_comboBox)
        self.t_submit_pb = QtWidgets.QPushButton(self.t_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_submit_pb.sizePolicy().hasHeightForWidth())
        self.t_submit_pb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.t_submit_pb.setFont(font)
        self.t_submit_pb.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 207, 215);\n"
"border-radius:7px;\n"
"color:white;\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(90, 147, 209); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(81, 122, 238); \n"
"}")
        self.t_submit_pb.setObjectName("t_submit_pb")
        self.verticalLayout_3.addWidget(self.t_submit_pb)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.setStretch(4, 1)
        self.verticalLayout_3.setStretch(6, 2)
        self.verticalLayout_3.setStretch(7, 1)
        self.horizontalLayout_2.addWidget(self.t_left_frame)
        self.t_right_frame = QtWidgets.QFrame(self.trans_page)
        self.t_right_frame.setStyleSheet("#t_right_frame{\n"
"border-radius:5px;\n"
"background-color: rgb(250, 250, 252);\n"
"}")
        self.t_right_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.t_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.t_right_frame.setObjectName("t_right_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.t_right_frame)
        self.verticalLayout_4.setSpacing(11)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.t_right_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.t_download_pb = QtWidgets.QPushButton(self.t_right_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.t_download_pb.setFont(font)
        self.t_download_pb.setStyleSheet("\n"
"QPushButton{\n"
"background:transparent;\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(225, 225, 225); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(255, 255, 255); \n"
"}")
        self.t_download_pb.setIcon(icon6)
        self.t_download_pb.setIconSize(QtCore.QSize(40, 40))
        self.t_download_pb.setObjectName("t_download_pb")
        self.horizontalLayout_9.addWidget(self.t_download_pb)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.t_result_tableWidget = QtWidgets.QTableWidget(self.t_right_frame)
        self.t_result_tableWidget.setStyleSheet("QTableWidget{\n"
"border-radius:7px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:2px solid rgb(176, 196, 234); \n"
"font: 75 9pt \"微软雅黑\";\n"
"}\n"
"\n"
"")
        self.t_result_tableWidget.setRowCount(0)
        self.t_result_tableWidget.setColumnCount(2)
        self.t_result_tableWidget.setObjectName("t_result_tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.t_result_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.t_result_tableWidget.setHorizontalHeaderItem(1, item)
        self.t_result_tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.t_result_tableWidget.horizontalHeader().setDefaultSectionSize(190)
        self.t_result_tableWidget.horizontalHeader().setHighlightSections(True)
        self.t_result_tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.t_result_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.t_result_tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.t_result_tableWidget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.t_result_tableWidget)
        self.horizontalLayout_2.addWidget(self.t_right_frame)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 2, 2)
        self.pages.addWidget(self.trans_page)
        self.about_page = QtWidgets.QWidget()
        self.about_page.setStyleSheet("")
        self.about_page.setObjectName("about_page")
        self.about_label = QtWidgets.QLabel(self.about_page)
        self.about_label.setGeometry(QtCore.QRect(10, 60, 921, 611))
        self.about_label.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(66, 115, 186, 255), stop:1 rgba(63, 158, 201, 255));\n"
"border-radius:10px;")
        self.about_label.setText("")
        self.about_label.setPixmap(QtGui.QPixmap(":/imgs/about_us.png"))
        self.about_label.setScaledContents(True)
        self.about_label.setObjectName("about_label")
        self.pages.addWidget(self.about_page)
        self.horizontalLayout_5.addWidget(self.pages)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(1)
        self.p_algo_tabWidget.setCurrentIndex(3)
        self.p_voc_comboBox.setCurrentIndex(0)
        self.p_jsc_comboBox.setCurrentIndex(0)
        self.p_ff_comboBox.setCurrentIndex(0)
        self.p_pce_comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于机器学习的有机光伏材料性能预测系统"))
        __sortingEnabled = self.leftList.isSortingEnabled()
        self.leftList.setSortingEnabled(False)
        item = self.leftList.item(0)
        item.setText(_translate("MainWindow", "    主 页"))
        item = self.leftList.item(1)
        item.setText(_translate("MainWindow", "  性能预测"))
        item = self.leftList.item(2)
        item.setText(_translate("MainWindow", "  指纹转换"))
        item = self.leftList.item(3)
        item.setText(_translate("MainWindow", "  关于我们"))
        self.leftList.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("MainWindow", "请输入SMILES："))
        self.p_example_pb.setText(_translate("MainWindow", "Example"))
        self.p_add_pb.setText(_translate("MainWindow", "+"))
        self.p_sub_pb.setText(_translate("MainWindow", "-"))
        self.p_help_pb.setText(_translate("MainWindow", "输入输出格式说明"))
        self.label_14.setText(_translate("MainWindow", "或从文件导入数据："))
        self.p_upload_pb.setText(_translate("MainWindow", "上传文件"))
        self.label_12.setText(_translate("MainWindow", "选择各属性使用算法："))
        self.p_voc_comboBox.setItemText(0, _translate("MainWindow", "Regression-Daylight-GBDT"))
        self.p_voc_comboBox.setItemText(1, _translate("MainWindow", "Regression-Daylight-RF"))
        self.p_voc_comboBox.setItemText(2, _translate("MainWindow", "Regression-Hy-GBDT"))
        self.p_voc_comboBox.setItemText(3, _translate("MainWindow", "Regression-Hy-RF"))
        self.p_voc_comboBox.setItemText(4, _translate("MainWindow", "Regression-Morgan-GBDT"))
        self.p_voc_comboBox.setItemText(5, _translate("MainWindow", "Regression-Morgan-RF"))
        self.p_voc_comboBox.setItemText(6, _translate("MainWindow", "Classification-Daylight-BP"))
        self.p_voc_comboBox.setItemText(7, _translate("MainWindow", "Classification-Daylight-RF"))
        self.p_voc_comboBox.setItemText(8, _translate("MainWindow", "Classification-Daylight-SVM"))
        self.p_voc_comboBox.setItemText(9, _translate("MainWindow", "Classification-Hy-BP"))
        self.p_voc_comboBox.setItemText(10, _translate("MainWindow", "Classification-Hy-RF"))
        self.p_voc_comboBox.setItemText(11, _translate("MainWindow", "Classification-Hy-SVM"))
        self.p_voc_comboBox.setItemText(12, _translate("MainWindow", "Classification-FP2-BP"))
        self.p_voc_comboBox.setItemText(13, _translate("MainWindow", "Classification-FP2-RF"))
        self.p_voc_comboBox.setItemText(14, _translate("MainWindow", "Classification-FP2-SVM"))
        self.p_voc_comboBox.setItemText(15, _translate("MainWindow", "Classification-Morgan-BP"))
        self.p_voc_comboBox.setItemText(16, _translate("MainWindow", "Classification-Morgan-RF"))
        self.p_voc_comboBox.setItemText(17, _translate("MainWindow", "Classification-Morgan-SVM"))
        self.p_algo_tabWidget.setTabText(self.p_algo_tabWidget.indexOf(self.voc_tab), _translate("MainWindow", "Voc(V)"))
        self.p_jsc_comboBox.setItemText(0, _translate("MainWindow", "Regression-Daylight-GBDT"))
        self.p_jsc_comboBox.setItemText(1, _translate("MainWindow", "Regression-Daylight-RF"))
        self.p_jsc_comboBox.setItemText(2, _translate("MainWindow", "Regression-Hy-GBDT"))
        self.p_jsc_comboBox.setItemText(3, _translate("MainWindow", "Regression-Hy-RF"))
        self.p_jsc_comboBox.setItemText(4, _translate("MainWindow", "Regression-Morgan-GBDT"))
        self.p_jsc_comboBox.setItemText(5, _translate("MainWindow", "Regression-Morgan-RF"))
        self.p_jsc_comboBox.setItemText(6, _translate("MainWindow", "Classification-Daylight-BP"))
        self.p_jsc_comboBox.setItemText(7, _translate("MainWindow", "Classification-Daylight-RF"))
        self.p_jsc_comboBox.setItemText(8, _translate("MainWindow", "Classification-Daylight-SVM"))
        self.p_jsc_comboBox.setItemText(9, _translate("MainWindow", "Classification-Hy-BP"))
        self.p_jsc_comboBox.setItemText(10, _translate("MainWindow", "Classification-Hy-RF"))
        self.p_jsc_comboBox.setItemText(11, _translate("MainWindow", "Classification-Hy-SVM"))
        self.p_jsc_comboBox.setItemText(12, _translate("MainWindow", "Classification-FP2-BP"))
        self.p_jsc_comboBox.setItemText(13, _translate("MainWindow", "Classification-FP2-RF"))
        self.p_jsc_comboBox.setItemText(14, _translate("MainWindow", "Classification-FP2-SVM"))
        self.p_jsc_comboBox.setItemText(15, _translate("MainWindow", "Classification-Morgan-BP"))
        self.p_jsc_comboBox.setItemText(16, _translate("MainWindow", "Classification-Morgan-RF"))
        self.p_jsc_comboBox.setItemText(17, _translate("MainWindow", "Classification-Morgan-SVM"))
        self.p_algo_tabWidget.setTabText(self.p_algo_tabWidget.indexOf(self.jsc_tab), _translate("MainWindow", "Jsc(mA/cm^2)"))
        self.p_ff_comboBox.setItemText(0, _translate("MainWindow", "Regression-Daylight-GBDT"))
        self.p_ff_comboBox.setItemText(1, _translate("MainWindow", "Regression-Daylight-RF"))
        self.p_ff_comboBox.setItemText(2, _translate("MainWindow", "Regression-Hy-GBDT"))
        self.p_ff_comboBox.setItemText(3, _translate("MainWindow", "Regression-Hy-RF"))
        self.p_ff_comboBox.setItemText(4, _translate("MainWindow", "Regression-Morgan-GBDT"))
        self.p_ff_comboBox.setItemText(5, _translate("MainWindow", "Regression-Morgan-RF"))
        self.p_ff_comboBox.setItemText(6, _translate("MainWindow", "Classification-Daylight-BP"))
        self.p_ff_comboBox.setItemText(7, _translate("MainWindow", "Classification-Daylight-RF"))
        self.p_ff_comboBox.setItemText(8, _translate("MainWindow", "Classification-Daylight-SVM"))
        self.p_ff_comboBox.setItemText(9, _translate("MainWindow", "Classification-Hy-BP"))
        self.p_ff_comboBox.setItemText(10, _translate("MainWindow", "Classification-Hy-RF"))
        self.p_ff_comboBox.setItemText(11, _translate("MainWindow", "Classification-Hy-SVM"))
        self.p_ff_comboBox.setItemText(12, _translate("MainWindow", "Classification-FP2-BP"))
        self.p_ff_comboBox.setItemText(13, _translate("MainWindow", "Classification-FP2-RF"))
        self.p_ff_comboBox.setItemText(14, _translate("MainWindow", "Classification-FP2-SVM"))
        self.p_ff_comboBox.setItemText(15, _translate("MainWindow", "Classification-Morgan-BP"))
        self.p_ff_comboBox.setItemText(16, _translate("MainWindow", "Classification-Morgan-RF"))
        self.p_ff_comboBox.setItemText(17, _translate("MainWindow", "Classification-Morgan-SVM"))
        self.p_algo_tabWidget.setTabText(self.p_algo_tabWidget.indexOf(self.ff_tab), _translate("MainWindow", "FF(%)"))
        self.p_pce_comboBox.setItemText(0, _translate("MainWindow", "Regression-Daylight-GBDT"))
        self.p_pce_comboBox.setItemText(1, _translate("MainWindow", "Regression-Daylight-RF"))
        self.p_pce_comboBox.setItemText(2, _translate("MainWindow", "Regression-Hy-GBDT"))
        self.p_pce_comboBox.setItemText(3, _translate("MainWindow", "Regression-Hy-RF"))
        self.p_pce_comboBox.setItemText(4, _translate("MainWindow", "Regression-Morgan-GBDT"))
        self.p_pce_comboBox.setItemText(5, _translate("MainWindow", "Regression-Morgan-RF"))
        self.p_pce_comboBox.setItemText(6, _translate("MainWindow", "Classification-Daylight-BP"))
        self.p_pce_comboBox.setItemText(7, _translate("MainWindow", "Classification-Daylight-RF"))
        self.p_pce_comboBox.setItemText(8, _translate("MainWindow", "Classification-Daylight-SVM"))
        self.p_pce_comboBox.setItemText(9, _translate("MainWindow", "Classification-Hy-BP"))
        self.p_pce_comboBox.setItemText(10, _translate("MainWindow", "Classification-Hy-RF"))
        self.p_pce_comboBox.setItemText(11, _translate("MainWindow", "Classification-Hy-SVM"))
        self.p_pce_comboBox.setItemText(12, _translate("MainWindow", "Classification-FP2-BP"))
        self.p_pce_comboBox.setItemText(13, _translate("MainWindow", "Classification-FP2-RF"))
        self.p_pce_comboBox.setItemText(14, _translate("MainWindow", "Classification-FP2-SVM"))
        self.p_pce_comboBox.setItemText(15, _translate("MainWindow", "Classification-Morgan-BP"))
        self.p_pce_comboBox.setItemText(16, _translate("MainWindow", "Classification-Morgan-RF"))
        self.p_pce_comboBox.setItemText(17, _translate("MainWindow", "Classification-Morgan-SVM"))
        self.p_algo_tabWidget.setTabText(self.p_algo_tabWidget.indexOf(self.pce_tab), _translate("MainWindow", "PCE(%)"))
        self.p_submit_pb.setText(_translate("MainWindow", "提交"))
        self.label_5.setText(_translate("MainWindow", "   预测结果："))
        self.p_download_pb.setText(_translate("MainWindow", "下载结果"))
        self.label_7.setText(_translate("MainWindow", "请输入SMILES："))
        self.t_example_pb.setText(_translate("MainWindow", "Example"))
        self.t_add_pb.setText(_translate("MainWindow", "+"))
        self.t_sub_pb.setText(_translate("MainWindow", "-"))
        self.t_help_pb.setText(_translate("MainWindow", "输入输出格式说明"))
        self.label_2.setText(_translate("MainWindow", "或从文件导入数据："))
        self.t_upload_pb.setText(_translate("MainWindow", "上传文件"))
        self.label_16.setText(_translate("MainWindow", "选择指纹类型："))
        self.t_smile_comboBox.setItemText(0, _translate("MainWindow", "MACCSFingerprint"))
        self.t_smile_comboBox.setItemText(1, _translate("MainWindow", "MorganFingerprint"))
        self.t_smile_comboBox.setItemText(2, _translate("MainWindow", "TopologicalTorsionFingerprint"))
        self.t_smile_comboBox.setItemText(3, _translate("MainWindow", "AtomPairFingerprint"))
        self.t_smile_comboBox.setItemText(4, _translate("MainWindow", "EstateFingerprint"))
        self.t_smile_comboBox.setItemText(5, _translate("MainWindow", "RDKFingerprint"))
        self.t_smile_comboBox.setItemText(6, _translate("MainWindow", "DaylightFingerprint"))
        self.t_smile_comboBox.setItemText(7, _translate("MainWindow", "PubchemFingerprint"))
        self.t_smile_comboBox.setItemText(8, _translate("MainWindow", "ExtendedFingerprint"))
        self.t_smile_comboBox.setItemText(9, _translate("MainWindow", "HybridizationFingerprint"))
        self.t_submit_pb.setText(_translate("MainWindow", "提交"))
        self.label_8.setText(_translate("MainWindow", "   转换结果："))
        self.t_download_pb.setText(_translate("MainWindow", "下载结果"))
        item = self.t_result_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "SMILES"))
        item = self.t_result_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "RESULT"))
from my_title_widget import MyTitleWidget
import all_resources_rc
