# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dell\Desktop\Metallographic-detection-platform-based-on-DL\my_message_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyMessageDialog(object):
    def setupUi(self, MyMessageDialog):
        MyMessageDialog.setObjectName("MyMessageDialog")
        MyMessageDialog.resize(400, 300)
        MyMessageDialog.setStyleSheet("#message_dialog{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 9pt \"微软雅黑\";\n"
"border-radius:4px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(MyMessageDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.ensure_pb = QtWidgets.QPushButton(MyMessageDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ensure_pb.sizePolicy().hasHeightForWidth())
        self.ensure_pb.setSizePolicy(sizePolicy)
        self.ensure_pb.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ensure_pb.setFont(font)
        self.ensure_pb.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 170, 0);\n"
"border-radius:7px;\n"
"color:white;\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(255, 255, 91); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(255, 255, 22); \n"
"}")
        self.ensure_pb.setObjectName("ensure_pb")
        self.gridLayout.addWidget(self.ensure_pb, 1, 0, 1, 1)
        self.info_text = QtWidgets.QTextBrowser(MyMessageDialog)
        self.info_text.setStyleSheet("border-radius:4px;")
        self.info_text.setObjectName("info_text")
        self.gridLayout.addWidget(self.info_text, 0, 0, 1, 1)

        self.retranslateUi(MyMessageDialog)
        QtCore.QMetaObject.connectSlotsByName(MyMessageDialog)

    def retranslateUi(self, MyMessageDialog):
        _translate = QtCore.QCoreApplication.translate
        MyMessageDialog.setWindowTitle(_translate("MyMessageDialog", "友情提醒！！！"))
        self.ensure_pb.setText(_translate("MyMessageDialog", "确定"))
        self.info_text.setHtml(_translate("MyMessageDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
import all_resources_rc
