# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dell\Desktop\Metallographic-detection-platform-based-on-DL\my_help_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyHelpDialog(object):
    def setupUi(self, MyHelpDialog):
        MyHelpDialog.setObjectName("MyHelpDialog")
        MyHelpDialog.resize(800, 600)
        MyHelpDialog.setStyleSheet("#help_dialog{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 9pt \"微软雅黑\";\n"
"border-radius:4px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(MyHelpDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.ensure_pb = QtWidgets.QPushButton(MyHelpDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ensure_pb.sizePolicy().hasHeightForWidth())
        self.ensure_pb.setSizePolicy(sizePolicy)
        self.ensure_pb.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ensure_pb.setFont(font)
        self.ensure_pb.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 170, 0);\n"
"border-radius:7px;\n"
"color:white;\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(255, 255, 91); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(255, 255, 22); \n"
"}")
        self.ensure_pb.setObjectName("ensure_pb")
        self.gridLayout.addWidget(self.ensure_pb, 1, 0, 1, 1)
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(MyHelpDialog)
        self.webEngineView.setUrl(QtCore.QUrl("qrc:/htmls/other_sources/input_output_help.html"))
        self.webEngineView.setObjectName("webEngineView")
        self.gridLayout.addWidget(self.webEngineView, 0, 0, 1, 1)

        self.retranslateUi(MyHelpDialog)
        QtCore.QMetaObject.connectSlotsByName(MyHelpDialog)

    def retranslateUi(self, MyHelpDialog):
        _translate = QtCore.QCoreApplication.translate
        MyHelpDialog.setWindowTitle(_translate("MyHelpDialog", "友情提醒！！！"))
        self.ensure_pb.setText(_translate("MyHelpDialog", "确定"))
from PyQt5 import QtWebEngineWidgets
import all_resources_rc
