# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dell\Desktop\Metallographic-detection-platform-based-on-DL\my_title_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyTitleWidget(object):
    def setupUi(self, MyTitleWidget):
        MyTitleWidget.setObjectName("MyTitleWidget")
        MyTitleWidget.resize(938, 68)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MyTitleWidget)
        self.horizontalLayout.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(MyTitleWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(60, 60))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/imgs/cqu_white.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.title_label = QtWidgets.QLabel(MyTitleWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color:white")
        self.title_label.setObjectName("title_label")
        self.horizontalLayout.addWidget(self.title_label)
        self.person_pb = QtWidgets.QLabel(MyTitleWidget)
        self.person_pb.setText("")
        self.person_pb.setPixmap(QtGui.QPixmap(":/imgs/person.png"))
        self.person_pb.setObjectName("person_pb")
        self.horizontalLayout.addWidget(self.person_pb)
        self.person_down_pb = QtWidgets.QPushButton(MyTitleWidget)
        self.person_down_pb.setStyleSheet("\n"
"QPushButton{\n"
"background:transparent;\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(225, 225, 225); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(255, 255, 255); \n"
"}")
        self.person_down_pb.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgs/arrow_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.person_down_pb.setIcon(icon)
        self.person_down_pb.setIconSize(QtCore.QSize(30, 30))
        self.person_down_pb.setObjectName("person_down_pb")
        self.horizontalLayout.addWidget(self.person_down_pb)
        self.min_pb = QtWidgets.QPushButton(MyTitleWidget)
        self.min_pb.setStyleSheet("\n"
"QPushButton{\n"
"background:transparent;\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(225, 225, 225); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(255, 255, 255); \n"
"}")
        self.min_pb.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/imgs/sub.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min_pb.setIcon(icon1)
        self.min_pb.setIconSize(QtCore.QSize(30, 30))
        self.min_pb.setObjectName("min_pb")
        self.horizontalLayout.addWidget(self.min_pb)
        self.max_pb = QtWidgets.QPushButton(MyTitleWidget)
        self.max_pb.setStyleSheet("\n"
"QPushButton{\n"
"background:transparent;\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(225, 225, 225); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(255, 255, 255); \n"
"}")
        self.max_pb.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/imgs/kou.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.max_pb.setIcon(icon2)
        self.max_pb.setIconSize(QtCore.QSize(30, 30))
        self.max_pb.setObjectName("max_pb")
        self.horizontalLayout.addWidget(self.max_pb)
        self.close_pb = QtWidgets.QPushButton(MyTitleWidget)
        self.close_pb.setStyleSheet("\n"
"QPushButton{\n"
"background:transparent;\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:hover \n"
"{ \n"
"    background-color: rgb(225, 225, 225); \n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    background-color: rgb(255, 255, 255); \n"
"}")
        self.close_pb.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/imgs/cha.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_pb.setIcon(icon3)
        self.close_pb.setIconSize(QtCore.QSize(30, 30))
        self.close_pb.setObjectName("close_pb")
        self.horizontalLayout.addWidget(self.close_pb)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(MyTitleWidget)
        QtCore.QMetaObject.connectSlotsByName(MyTitleWidget)

    def retranslateUi(self, MyTitleWidget):
        _translate = QtCore.QCoreApplication.translate
        MyTitleWidget.setWindowTitle(_translate("MyTitleWidget", "Form"))
        self.title_label.setText(_translate("MyTitleWidget", " 基于机器学习的有机光伏材料性能预测系统"))
import all_resources_rc
